Auto commit

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -19,21 +19,43 @@ fi
 echo
 echo -e "${GREEN}Installing packages...${ENDCOLOR}"
 echo
-pkgs=(zsh curl git make unzip gcc ripgrep tmux firefox)
+pkgs=(zsh curl git make unzip gcc ripgrep tmux openssh openssh-client openssh-server firefox)
 
 # apt
 if command -v apt-get >/dev/null 2>&1; then
     sudo apt-get update
     sudo apt-get upgrade -y
     sudo apt-get -y --ignore-missing install "${pkgs[@]}"
+
+    for pkg in "${pkgs[@]}"; do
+        sudo apt-get --ignore-missing -y install "$pkg"
+        if [[ $? -ne 0 ]]; then
+            echo -e "${YELLOW}Warning:${ENDCOLOR} Package $pkg not found, skipping..."
+        else
+            echo -e "${GREEN}Package $pkg installed successfully.${ENDCOLOR}"
+        fi
+    done
+
 # pacman
 elif command -v pacman >/dev/null 2>&1; then
     sudo pacman -Syu --noconfirm
     sudo pacman -S --noconfirm --needed "${pkgs[@]}"
+
+    for pkg in "${pkgs[@]}"; do
+        sudo pacman -S --noconfirm --need "$pkg"
+        if [[ $? -ne 0 ]]; then
+            echo -e "${YELLOW}Warning:${ENDCOLOR} Package $pkg not found, skipping..."
+        else
+            echo -e "${GREEN}Package $pkg installed successfully.${ENDCOLOR}"
+        fi
+    done
+
+    echo -e "${GREEN}Installing yay...${ENDCOLOR}"
+    sudo pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si
 fi
 
 echo
-echo -e "${GREEN}Installing Oh My Zsh and powerlevel10k...${ENDCOLOR}"
+echo -e "${GREEN}Installing Oh My Zsh and Powerlevel10k...${ENDCOLOR}"
 echo
 ZSH_PATH=$(which zsh)
 if [[ $ZSH_PATH =~ "sbin" ]]; then
