Auto commit

diff --git a/.config/zsh-custom/env b/.config/zsh-custom/env
--- a/.config/zsh-custom/env
+++ b/.config/zsh-custom/env
@@ -13,6 +13,15 @@ addToPathFront() {
     fi
 }
 
+venv() {
+    if [[ ! -f ./.venv/Scripts/activate ]]; then
+        echo "venv script not found. Use 'python -m venv .venv' to create new virtual environment!"
+	exit 1
+    fi
+
+    source ./.venv/Scripts/activate
+}
+
 # Custom environment variables
 export LANG=en_US.UTF-8
 export GIT_EDITOR=nvim
